# 01. Data Extraction, Transformation and Initial Preparation

The data set consists of hourly measurements of 882 days from 19 July 2011 to 31 December 2013, a file per each day. These files were in either xml or xlsx formats. These files were converted to csv format in order to reduce the file size and for ease of extraction. Then they were saved in separate folders in monthly and yearly basis before extraction of data. After that, these files were extracted and pre-processed separately

## 1.1 Import Libraries

In [39]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import glob

## 1.2 Configuration

In [40]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

## 1.3 Extract 2011 data

In [41]:
# specifiying the path in the csv files
path_2011_Jul = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\Semester - 3\\Project\\Data\\SEA\\2011 Jul'
path_2011_Aug = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2011 Aug'
path_2011_Sep = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2011 Sep'
path_2011_Oct = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\Semester - 3\\Project\\Data\\SEA\\2011 Oct'
path_2011_Nov = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2011 Nov'
path_2011_Dec = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2011 Dec'

path = [path_2011_Jul,path_2011_Aug,path_2011_Sep,path_2011_Oct,path_2011_Nov,path_2011_Dec]

In [42]:
# defining an empty list to store content
data_frame_2011 = pd.DataFrame()
content = []

for files in path:
    csv_files = glob.glob(files + "/*.csv")
    
    # loop over the list of csv files
    for f in csv_files:
  
        # read the csv file
        df = pd.read_csv(f)
        
        # drop 1st raw
        df.drop([0], inplace=True)
        
        # insert day column
        day = f.split("\\")[-1].split(' ')[0].split('.')[-2]
        df.insert(0,'Day',day)
    
        # content.append(f)
        content.append(df)

# converting content to data frame
data_frame_2011 = pd.concat(content)

# Remove '\n' characters
data_frame_2011 = data_frame_2011.replace('\n','', regex=True)

# Rename Columns
data_frame_2011.rename(columns = {'Time\n':'Time','Mean\n':'MeanWS','Unnamed: 2':'MeanWD','Max Gust\n':'MaxGustWS','Unnamed: 4':'MaxGustWD',
                         'Open Air Temperature(deg.C)\n':'OpenAirTempInst','Unnamed: 6':'OpenAirTempMax','Unnamed: 7':'OpenAirTempMin',
                        'Module Temperature 1(deg.C)\n':'Module1TempInst','Unnamed: 9':'Module1TempMax','Unnamed: 10':'Module1TempMin',
                        'Module Temperature 2(deg.C)\n':'Module2TempInst','Unnamed: 12':'Module2TempMax','Unnamed: 13':'Module2TempMin',
                        'Module Temperature 3(deg.C)\n':'Module3TempInst','Unnamed: 15':'Module3TempMax','Unnamed: 16':'Module3TempMin',
                        'Module Temperature 4(deg.C)\n':'Module4TempInst','Unnamed: 18':'Module4TempMax','Unnamed: 19':'Module4TempMin',
                        'Module Temperature 5(deg.C)\n':'Module5TempInst','Unnamed: 21':'Module5TempMax','Unnamed: 22':'Module5TempMin',
                        'Module Temperature 6(deg.C)\n':'Module6TempInst','Unnamed: 24':'Module6TempMax','Unnamed: 25':'Module6TempMin',
                        'Generating Power(kW)\n':'PowerInst','Unnamed: 31':'PowerMax','Unnamed: 32':'PowerMin','Precipitation\n(mm)\n':'Precipitation',
                        'Pyranometer\n(MJ/m2)\n':'GlobalSolarRadiation','Tilt Solar Irradiance (MJ/m2)\n':'TiltSolarIrradiance',
                        'Diffuse Solar Irradiance (MJ/m2)\n':'DiffuseSolarIrradiance','Power Generation (kWh)\n': 'Energy','CO2\nReduction\n(c-kg)\n':'CO2Reduction'},inplace=True)

# Change data type
num_cols = ['MeanWS','MaxGustWS','OpenAirTempInst','OpenAirTempMax','OpenAirTempMin','Module1TempInst','Module1TempMax',
 'Module1TempMin','Module2TempInst','Module2TempMax','Module2TempMin','Module3TempInst','Module3TempMax','Module3TempMin',
 'Module4TempInst','Module4TempMax','Module4TempMin','Module5TempInst','Module5TempMax','Module5TempMin','Module6TempInst',
 'Module6TempMax','Module6TempMin','Precipitation','GlobalSolarRadiation','TiltSolarIrradiance','DiffuseSolarIrradiance','PowerInst',
 'PowerMax','PowerMin','Energy','CO2Reduction']
data_frame_2011[num_cols] = data_frame_2011[num_cols].apply(pd.to_numeric)

# Add date column
data_frame_2011['Time1'] = pd.to_timedelta(data_frame_2011['Time'] + ':00')
data_frame_2011["Date"] = pd.to_datetime(data_frame_2011["Day"]) + pd.to_timedelta(data_frame_2011["Time1"])

# shift the Date column to first position
first_column = data_frame_2011.pop('Date')
data_frame_2011.insert(0,'Date',first_column)

# Drop Time1 columns
data_frame_2011.drop(['Time1'],axis=1,inplace=True)

# Set date column as index
data_frame_2011.set_index("Date")

# drop NAN raws
data_frame_2011.dropna(axis=0, subset=['MeanWS'], inplace=True)

data_frame_2011.head()

,Date,Day,Time,MeanWS,MeanWD,MaxGustWS,MaxGustWD,OpenAirTempInst,OpenAirTempMax,OpenAirTempMin,Module1TempInst,Module1TempMax,Module1TempMin,Module2TempInst,Module2TempMax,Module2TempMin,Module3TempInst,Module3TempMax,Module3TempMin,Module4TempInst,Module4TempMax,Module4TempMin,Module5TempInst,Module5TempMax,Module5TempMin,Module6TempInst,Module6TempMax,Module6TempMin,Precipitation,GlobalSolarRadiation,TiltSolarIrradiance,DiffuseSolarIrradiance,PowerInst,PowerMax,PowerMin,Energy,CO2Reduction
1,2011-07-21 01:00:00,2011-07-21,01:00,5.0,WSW,8.2,WSW,25.6,25.6,25.5,23.9,24.0,23.8,23.4,23.5,23.3,23.4,23.4,23.2,23.0,23.0,22.9,23.3,23.4,23.2,23.8,23.8,23.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2011-07-21 02:00:00,2011-07-21,02:00,3.6,WSW,6.8,SW,25.5,25.6,25.4,24.2,24.2,23.8,23.7,23.7,23.4,23.6,23.6,23.2,23.4,23.4,22.8,23.6,23.6,23.1,24.1,24.1,23.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2011-07-21 03:00:00,2011-07-21,03:00,4.0,WSW,6.7,WSW,25.7,25.8,25.5,23.8,24.2,23.7,23.3,23.7,23.2,23.2,23.6,23.1,23.0,23.5,22.9,23.3,23.8,23.2,23.8,24.4,23.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2011-07-21 04:00:00,2011-07-21,04:00,3.2,WSW,5.9,WSW,25.3,25.7,25.3,23.4,24.0,23.4,23.0,23.5,23.0,22.9,23.4,22.9,22.5,23.2,22.5,22.8,23.5,22.8,23.3,24.0,23.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2011-07-21 05:00:00,2011-07-21,05:00,3.8,WSW,5.5,WSW,25.2,25.4,25.1,23.3,23.5,23.3,22.8,23.0,22.8,22.8,22.9,22.7,22.3,22.5,22.3,22.6,22.8,22.6,23.1,23.2,23.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
data_frame_2011.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3926 entries, 1 to 24
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    3926 non-null   datetime64[ns]
 1   Day                     3926 non-null   object
 2   Time                    3926 non-null   object
 3   MeanWS                  3926 non-null   float64
 4   MeanWD                  3926 non-null   object
 5   MaxGustWS               3926 non-null   float64
 6   MaxGustWD               3926 non-null   object
 7   OpenAirTempInst         3926 non-null   float64
 8   OpenAirTempMax          3926 non-null   float64
 9   OpenAirTempMin          3926 non-null   float64
 10  Module1TempInst         3926 non-null   float64
 11  Module1TempMax          3926 non-null   float64
 12  Module1TempMin          3926 non-null   float64
 13  Module2TempInst         3926 non-null   float64
 14  Module2TempMax          3926 non-null   float64
 15  Module2TempMin          3926 non-null   float64
 16  Module3TempInst         3926 non-null   float64
 17  Module3TempMax          3926 non-null   float64
 18  Module3TempMin          3926 non-null   float64
 19  Module4TempInst         3926 non-null   float64
 20  Module4TempMax          3926 non-null   float64
 21  Module4TempMin          3926 non-null   float64
 22  Module5TempInst         3926 non-null   float64
 23  Module5TempMax          3926 non-null   float64
 24  Module5TempMin          3926 non-null   float64
 25  Module6TempInst         3926 non-null   float64
 26  Module6TempMax          3926 non-null   float64
 27  Module6TempMin          3926 non-null   float64
 28  Precipitation           3842 non-null   float64
 29  GlobalSolarRadiation    3926 non-null   float64
 30  TiltSolarIrradiance     3926 non-null   float64
 31  DiffuseSolarIrradiance  3926 non-null   float64
 32  PowerInst               3896 non-null   float64
 33  PowerMax                3914 non-null   float64
 34  PowerMin                3914 non-null   float64
 35  Energy                  3926 non-null   float64
 36  CO2Reduction            3926 non-null   float64
dtypes: datetime64[ns](1), float64(32), object(4)
memory usage: 1.1+ MB

In [44]:
#Save data in csv format
data_frame_2011.to_csv('Data_2011.csv',index=False)

## 1.4 Extract 2012 data

Jan - Nov data files are in XML format. Dec data is in xlsx format. These files were converted in to csv before extraction.

In [45]:
# specifiying the path in the csv files
path_2012_Jan = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\Semester - 3\\Project\\Data\\SEA\\2012 Jan'
path_2012_Feb = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2012 Feb'
path_2012_Mar = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2012 Mar'
path_2012_Apr = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\Semester - 3\\Project\\Data\\SEA\\2012 Apr'
path_2012_May = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2012 May'
path_2012_Jun = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2012 Jun'
path_2012_Jul = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\Semester - 3\\Project\\Data\\SEA\\2012 Jul'
path_2012_Aug = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2012 Aug'
path_2012_Sep = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2012 Sep'
path_2012_Oct = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\Semester - 3\\Project\\Data\\SEA\\2012 Oct'
path_2012_Nov = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2012 Nov'

path = [path_2012_Jan,path_2012_Feb,path_2012_Mar,path_2012_Apr,path_2012_May,path_2012_Jun,path_2012_Jul,path_2012_Aug,path_2012_Sep,path_2012_Oct,path_2012_Nov]

#### Extract Jan - Nov 2012 Data (XML format)

In [46]:
# defining an empty list to store content
data_frame_2012 = pd.DataFrame()
content = []

for files in path:
    csv_files = glob.glob(files + "/*.csv")
    
    # loop over the list of csv files
    for f in csv_files:
  
        # read the csv file
        df = pd.read_csv(f)
        
         # drop raws
        df.drop([0], inplace=True)
        
        # insert day column
        day = f.split("\\")[-1].split(' ')[0].split('.')[-2]
        df.insert(0,'Day',day)
    
        # content.append(f)
        content.append(df)

# converting content to data frame
data_frame_2012 = pd.concat(content)

# Remove '\n' 
data_frame_2012 = data_frame_2012.replace('\n','', regex=True)

# Rename Columns
data_frame_2012.rename(columns = {'Time\n':'Time','Mean\n':'MeanWS','Unnamed: 2':'MeanWD','Max Gust\n':'MaxGustWS','Unnamed: 4':'MaxGustWD',
                         'Open Air Temperature(deg.C)\n':'OpenAirTempInst','Unnamed: 6':'OpenAirTempMax','Unnamed: 7':'OpenAirTempMin',
                        'Module Temperature 1(deg.C)\n':'Module1TempInst','Unnamed: 9':'Module1TempMax','Unnamed: 10':'Module1TempMin',
                        'Module Temperature 2(deg.C)\n':'Module2TempInst','Unnamed: 12':'Module2TempMax','Unnamed: 13':'Module2TempMin',
                        'Module Temperature 3(deg.C)\n':'Module3TempInst','Unnamed: 15':'Module3TempMax','Unnamed: 16':'Module3TempMin',
                        'Module Temperature 4(deg.C)\n':'Module4TempInst','Unnamed: 18':'Module4TempMax','Unnamed: 19':'Module4TempMin',
                        'Module Temperature 5(deg.C)\n':'Module5TempInst','Unnamed: 21':'Module5TempMax','Unnamed: 22':'Module5TempMin',
                        'Module Temperature 6(deg.C)\n':'Module6TempInst','Unnamed: 24':'Module6TempMax','Unnamed: 25':'Module6TempMin',
                        'Generating Power(kW)\n':'PowerInst','Unnamed: 31':'PowerMax','Unnamed: 32':'PowerMin','Precipitation\n(mm)\n':'Precipitation',
                        'Pyranometer\n(MJ/m2)\n':'GlobalSolarRadiation','Tilt Solar Irradiance (MJ/m2)\n':'TiltSolarIrradiance',
                        'Diffuse Solar Irradiance (MJ/m2)\n':'DiffuseSolarIrradiance','Power Generation (kWh)\n': 'Energy','CO2\nReduction\n(c-kg)\n':'CO2Reduction'},inplace=True)


# Change data type
num_cols = ['MeanWS','MaxGustWS','OpenAirTempInst','OpenAirTempMax','OpenAirTempMin','Module1TempInst','Module1TempMax',
 'Module1TempMin','Module2TempInst','Module2TempMax','Module2TempMin','Module3TempInst','Module3TempMax','Module3TempMin',
 'Module4TempInst','Module4TempMax','Module4TempMin','Module5TempInst','Module5TempMax','Module5TempMin','Module6TempInst',
 'Module6TempMax','Module6TempMin','Precipitation','GlobalSolarRadiation','TiltSolarIrradiance','DiffuseSolarIrradiance','PowerInst',
 'PowerMax','PowerMin','Energy','CO2Reduction']

data_frame_2012[num_cols] = data_frame_2012[num_cols].apply(pd.to_numeric)


#data_frame_2012['Time'] = pd.to_timedelta(data_frame_2012.pop('Time') + ':00')
data_frame_2012['Time1'] = pd.to_timedelta(data_frame_2012['Time'] + ':00')

# Add date column
data_frame_2012["Date"] = pd.to_datetime(data_frame_2012["Day"]) + pd.to_timedelta(data_frame_2012["Time1"])

# shift the Date column to first position
first_column = data_frame_2012.pop('Date')
data_frame_2012.insert(0,'Date',first_column)

# Drop Time1 column
data_frame_2012.drop(['Time1'],axis=1,inplace=True)

data_frame_2012.set_index("Date")

# drop NAN raws
data_frame_2012.dropna(axis=0, subset=['MeanWS'], inplace=True)

data_frame_2012.head()

,Date,Day,Time,MeanWS,MeanWD,MaxGustWS,MaxGustWD,OpenAirTempInst,OpenAirTempMax,OpenAirTempMin,Module1TempInst,Module1TempMax,Module1TempMin,Module2TempInst,Module2TempMax,Module2TempMin,Module3TempInst,Module3TempMax,Module3TempMin,Module4TempInst,Module4TempMax,Module4TempMin,Module5TempInst,Module5TempMax,Module5TempMin,Module6TempInst,Module6TempMax,Module6TempMin,Precipitation,GlobalSolarRadiation,TiltSolarIrradiance,DiffuseSolarIrradiance,PowerInst,PowerMax,PowerMin,Energy,CO2Reduction
1,2012-01-01 01:00:00,2012-01-01,01:00,2.3,ENE,2.7,ENE,22.3,22.9,22.2,20.0,20.2,20.0,19.0,19.6,19.0,19.3,19.4,19.0,18.4,18.5,18.3,18.5,18.6,18.4,19.1,19.1,18.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2012-01-01 02:00:00,2012-01-01,02:00,1.7,NE,2.3,ENE,22.3,22.5,21.8,19.6,20.0,19.4,19.1,19.5,18.7,19.3,19.4,18.9,18.7,18.7,18.3,18.6,18.8,18.4,19.2,19.4,19.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2012-01-01 03:00:00,2012-01-01,03:00,2.1,NE,2.4,NE,22.0,22.3,21.9,19.9,19.9,19.3,19.5,19.6,18.7,19.0,19.3,18.9,18.3,18.7,18.3,18.3,18.6,18.2,19.0,19.3,18.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2012-01-01 04:00:00,2012-01-01,04:00,2.2,NNE,2.6,NNE,21.5,22.0,21.4,19.4,19.9,19.4,18.8,19.5,18.8,19.0,19.3,18.8,18.4,18.4,18.1,18.7,18.8,18.1,19.4,19.6,18.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2012-01-01 05:00:00,2012-01-01,05:00,2.2,NNE,3.0,NNE,21.9,22.2,21.6,19.5,19.7,19.4,18.8,19.2,18.6,19.1,19.3,18.9,18.5,18.5,18.2,18.6,18.6,18.3,19.2,19.4,18.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
data_frame_2012.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8040 entries, 1 to 24
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    8040 non-null   datetime64[ns]
 1   Day                     8040 non-null   object
 2   Time                    8040 non-null   object
 3   MeanWS                  8040 non-null   float64
 4   MeanWD                  8040 non-null   object
 5   MaxGustWS               8040 non-null   float64
 6   MaxGustWD               8040 non-null   object
 7   OpenAirTempInst         8040 non-null   float64
 8   OpenAirTempMax          8040 non-null   float64
 9   OpenAirTempMin          8040 non-null   float64
 10  Module1TempInst         8040 non-null   float64
 11  Module1TempMax          8040 non-null   float64
 12  Module1TempMin          8040 non-null   float64
 13  Module2TempInst         8040 non-null   float64
 14  Module2TempMax          8040 non-null   float64
 15  Module2TempMin          8040 non-null   float64
 16  Module3TempInst         8040 non-null   float64
 17  Module3TempMax          8040 non-null   float64
 18  Module3TempMin          8040 non-null   float64
 19  Module4TempInst         8040 non-null   float64
 20  Module4TempMax          8040 non-null   float64
 21  Module4TempMin          8040 non-null   float64
 22  Module5TempInst         8040 non-null   float64
 23  Module5TempMax          8040 non-null   float64
 24  Module5TempMin          8040 non-null   float64
 25  Module6TempInst         8040 non-null   float64
 26  Module6TempMax          8040 non-null   float64
 27  Module6TempMin          8040 non-null   float64
 28  Precipitation           8040 non-null   float64
 29  GlobalSolarRadiation    8040 non-null   float64
 30  TiltSolarIrradiance     8040 non-null   float64
 31  DiffuseSolarIrradiance  8040 non-null   float64
 32  PowerInst               7978 non-null   float64
 33  PowerMax                8006 non-null   float64
 34  PowerMin                8006 non-null   float64
 35  Energy                  8040 non-null   float64
 36  CO2Reduction            8040 non-null   float64
dtypes: datetime64[ns](1), float64(32), object(4)
memory usage: 2.3+ MB

In [48]:
#Save data in csv format
data_frame_2012.to_csv('Data_2012_Jan_Nov.csv',index=False)

#### Extract Dec 2012 Data (xlsx format)

In [49]:
path_2012_Dec = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2012 Dec'

csv_files = glob.glob(path_2012_Dec + "/*.csv")

# defining an empty list to store content
data_frame_2012_Dec = pd.DataFrame()
content = []
    
# loop over the list of csv files
for f in csv_files:
  
    # read the csv file
    df = pd.read_csv(f)
        
    # drop raws
    df.drop([0], inplace=True)
        
    # insert day column
    day = f.split("\\")[-1].split(' ')[0].split('.')[-2]
    df.insert(0,'Day',day)
    
    # content.append(f)
    content.append(df)

# converting content to data frame
data_frame_2012_Dec = pd.concat(content)

# Rename Columns
data_frame_2012_Dec.rename(columns = {'Mean':'MeanWS','Unnamed: 2':'MeanWD','Max Gust':'MaxGustWS','Unnamed: 4':'MaxGustWD',
                         'Open Air Temperature(deg.C)':'OpenAirTempInst','Unnamed: 6':'OpenAirTempMax','Unnamed: 7':'OpenAirTempMin',
                        'Module Temperature 1(deg.C)':'Module1TempInst','Unnamed: 9':'Module1TempMax','Unnamed: 10':'Module1TempMin',
                        'Module Temperature 2(deg.C)':'Module2TempInst','Unnamed: 12':'Module2TempMax','Unnamed: 13':'Module2TempMin',
                        'Module Temperature 3(deg.C)':'Module3TempInst','Unnamed: 15':'Module3TempMax','Unnamed: 16':'Module3TempMin',
                        'Module Temperature 4(deg.C)':'Module4TempInst','Unnamed: 18':'Module4TempMax','Unnamed: 19':'Module4TempMin',
                        'Module Temperature 5(deg.C)':'Module5TempInst','Unnamed: 21':'Module5TempMax','Unnamed: 22':'Module5TempMin',
                        'Module Temperature 6(deg.C)':'Module6TempInst','Unnamed: 24':'Module6TempMax','Unnamed: 25':'Module6TempMin',
                        'Generating Power(kW)':'PowerInst','Unnamed: 31':'PowerMax','Unnamed: 32':'PowerMin','Precipitation\n\n(mm)':'Precipitation',
                        'Pyranometer\n\n(MJ/m2)':'GlobalSolarRadiation','Tilt Solar Irradiance (MJ/m2)':'TiltSolarIrradiance',
                        'Diffuse Solar Irradiance (MJ/m2)':'DiffuseSolarIrradiance','Power Generation (kWh)': 'Energy','CO2\nReduction\n(c-kg)':'CO2Reduction'},inplace=True)


# Change data type
num_cols = ['MeanWS','MaxGustWS','OpenAirTempInst','OpenAirTempMax','OpenAirTempMin','Module1TempInst','Module1TempMax',
 'Module1TempMin','Module2TempInst','Module2TempMax','Module2TempMin','Module3TempInst','Module3TempMax','Module3TempMin',
 'Module4TempInst','Module4TempMax','Module4TempMin','Module5TempInst','Module5TempMax','Module5TempMin','Module6TempInst',
 'Module6TempMax','Module6TempMin','Precipitation','GlobalSolarRadiation','TiltSolarIrradiance','DiffuseSolarIrradiance','PowerInst',
 'PowerMax','PowerMin','Energy','CO2Reduction']

data_frame_2012_Dec[num_cols] = data_frame_2012_Dec[num_cols].apply(pd.to_numeric)

# Add date column
data_frame_2012_Dec["Date"] = pd.to_datetime(data_frame_2012_Dec["Day"]) + pd.to_timedelta(data_frame_2012_Dec["Time"])

# shift the Date column to first position
first_column = data_frame_2012_Dec.pop('Date')
data_frame_2012_Dec.insert(0,'Date',first_column)

# Drop Day and Time columns
#data_frame_2012_Dec.drop(['Day','Time'],axis=1,inplace=True)

data_frame_2012_Dec.set_index("Date")

# drop NAN raws
data_frame_2012_Dec.dropna(axis=0, subset=['MeanWS'], inplace=True)

data_frame_2012_Dec.head()

,Date,Day,Time,MeanWS,MeanWD,MaxGustWS,MaxGustWD,OpenAirTempInst,OpenAirTempMax,OpenAirTempMin,Module1TempInst,Module1TempMax,Module1TempMin,Module2TempInst,Module2TempMax,Module2TempMin,Module3TempInst,Module3TempMax,Module3TempMin,Module4TempInst,Module4TempMax,Module4TempMin,Module5TempInst,Module5TempMax,Module5TempMin,Module6TempInst,Module6TempMax,Module6TempMin,Precipitation,GlobalSolarRadiation,TiltSolarIrradiance,DiffuseSolarIrradiance,PowerInst,PowerMax,PowerMin,Energy,CO2Reduction
1,2012-12-01 01:00:00,2012-12-01,01:00:00,1.9,NNE,2.6,NNE,22.5,22.9,22.5,20.3,20.9,20.3,19.7,20.2,19.6,19.6,20.1,19.6,19.0,19.7,19.0,19.4,20.1,19.4,19.8,20.4,19.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
2,2012-12-01 02:00:00,2012-12-01,02:00:00,1.6,NE,2.4,NE,22.5,22.7,22.3,20.6,20.6,20.1,19.8,19.8,19.4,19.6,19.6,19.3,19.1,19.1,18.7,19.4,19.4,19.1,19.7,19.8,19.4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0.0
3,2012-12-01 03:00:00,2012-12-01,03:00:00,1.8,NE,3.1,NE,22.3,22.6,22.3,20.9,21.0,20.6,20.2,20.2,19.8,20.1,20.1,19.7,19.5,19.5,19.1,19.9,19.9,19.4,20.2,20.2,19.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
4,2012-12-01 04:00:00,2012-12-01,04:00:00,1.9,NE,2.7,NNE,22.0,22.4,22.0,20.8,20.9,20.8,20.1,20.2,20.1,20.0,20.1,20.0,19.4,19.5,19.4,19.8,19.9,19.8,20.2,20.2,20.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
5,2012-12-01 05:00:00,2012-12-01,05:00:00,2.2,NNE,4.0,NNE,22.6,22.8,22.0,20.8,20.9,20.8,20.1,20.1,20.0,19.9,20.0,19.9,19.3,19.5,19.3,19.7,19.8,19.7,20.1,20.2,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0

In [50]:
#Save data in csv format
data_frame_2012_Dec.to_csv('Data_2012_Dec.csv',index=False)

In [51]:
## Add 2 data frames
data_frame_2012_all = data_frame_2012.append(data_frame_2012_Dec,ignore_index=True)

In [52]:
data_frame_2012_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    8784 non-null   datetime64[ns]
 1   Day                     8784 non-null   object
 2   Time                    8784 non-null   object
 3   MeanWS                  8784 non-null   float64
 4   MeanWD                  8784 non-null   object
 5   MaxGustWS               8784 non-null   float64
 6   MaxGustWD               8784 non-null   object
 7   OpenAirTempInst         8784 non-null   float64
 8   OpenAirTempMax          8784 non-null   float64
 9   OpenAirTempMin          8784 non-null   float64
 10  Module1TempInst         8784 non-null   float64
 11  Module1TempMax          8784 non-null   float64
 12  Module1TempMin          8784 non-null   float64
 13  Module2TempInst         8784 non-null   float64
 14  Module2TempMax          8784 non-null   float64
 15  Module2TempMin          8784 non-null   float64
 16  Module3TempInst         8784 non-null   float64
 17  Module3TempMax          8784 non-null   float64
 18  Module3TempMin          8784 non-null   float64
 19  Module4TempInst         8784 non-null   float64
 20  Module4TempMax          8784 non-null   float64
 21  Module4TempMin          8784 non-null   float64
 22  Module5TempInst         8784 non-null   float64
 23  Module5TempMax          8784 non-null   float64
 24  Module5TempMin          8784 non-null   float64
 25  Module6TempInst         8784 non-null   float64
 26  Module6TempMax          8784 non-null   float64
 27  Module6TempMin          8784 non-null   float64
 28  Precipitation           8784 non-null   float64
 29  GlobalSolarRadiation    8784 non-null   float64
 30  TiltSolarIrradiance     8784 non-null   float64
 31  DiffuseSolarIrradiance  8784 non-null   float64
 32  PowerInst               8714 non-null   float64
 33  PowerMax                8745 non-null   float64
 34  PowerMin                8745 non-null   float64
 35  Energy                  8784 non-null   float64
 36  CO2Reduction            8784 non-null   float64
dtypes: datetime64[ns](1), float64(32), object(4)
memory usage: 2.5+ MB

In [53]:
#Save data in csv format
data_frame_2012_all.to_csv('Data_2012.csv',index=False)

## 1.5 Extract 2013 data

#### Extract and preprocess 2013_Jan to 2013_August, 2013_December

In [54]:
# specifiying the path in the csv files
path_2013_Jan = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Jan'
path_2013_Feb = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Feb'
path_2013_Mar = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Mar'
path_2013_Apr = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Apr'
path_2013_May = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 May'
path_2013_Jun = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Jun'
path_2013_Jul = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Jul'
path_2013_Aug = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Aug'
path_2013_Dec = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Dec'

path = [path_2013_Jan,path_2013_Feb,path_2013_Mar,path_2013_Apr,path_2013_May,path_2013_Jun,path_2013_Jul,path_2013_Aug,path_2013_Dec]

In [55]:
# defining an empty list to store content
data_frame = pd.DataFrame()
content = []

for files in path:
    csv_files = glob.glob(files + "/*.csv")
    #csv_files = sorted(glob.glob(os.path.join(path,"*.xlsx")),key = len)

    # loop over the list of csv files
    for f in csv_files:
  
        # read the csv file
        df = pd.read_csv(f)
        
         # drop raws
        df.drop([0], inplace=True)
        
        # insert day column
        day = f.split("\\")[-1].split(' ')[0].split('.')[-2]
        df.insert(0,'Day',day)
    
        # content.append(f)
        content.append(df)

# converting content to data frame
data_frame = pd.concat(content)

# Rename Columns
data_frame.rename(columns = {'Mean':'MeanWS','Unnamed: 2':'MeanWD','Max Gust':'MaxGustWS','Unnamed: 4':'MaxGustWD',
                         'Open Air Temperature(deg.C)':'OpenAirTempInst','Unnamed: 6':'OpenAirTempMax','Unnamed: 7':'OpenAirTempMin',
                        'Module Temperature 1(deg.C)':'Module1TempInst','Unnamed: 9':'Module1TempMax','Unnamed: 10':'Module1TempMin',
                        'Module Temperature 2(deg.C)':'Module2TempInst','Unnamed: 12':'Module2TempMax','Unnamed: 13':'Module2TempMin',
                        'Module Temperature 3(deg.C)':'Module3TempInst','Unnamed: 15':'Module3TempMax','Unnamed: 16':'Module3TempMin',
                        'Module Temperature 4(deg.C)':'Module4TempInst','Unnamed: 18':'Module4TempMax','Unnamed: 19':'Module4TempMin',
                        'Module Temperature 5(deg.C)':'Module5TempInst','Unnamed: 21':'Module5TempMax','Unnamed: 22':'Module5TempMin',
                        'Module Temperature 6(deg.C)':'Module6TempInst','Unnamed: 24':'Module6TempMax','Unnamed: 25':'Module6TempMin',
                        'Generating Power(kW)':'PowerInst','Unnamed: 31':'PowerMax','Unnamed: 32':'PowerMin','Precipitation\n\n(mm)':'Precipitation',
                        'Pyranometer\n\n(MJ/m2)':'GlobalSolarRadiation','Tilt Solar Irradiance (MJ/m2)':'TiltSolarIrradiance',
                        'Diffuse Solar Irradiance (MJ/m2)':'DiffuseSolarIrradiance','Power Generation (kWh)': 'Energy','CO2\nReduction\n(c-kg)':'CO2Reduction'},inplace=True)

# drop columns
data_frame.drop(['Unnamed: 35','Time (hrs)','Mean Module Temperature (deg oC)','Mean Open Air Temperature (deg oC)',
             'Global horizontal irradiance (GHI) W/m2','Tilt solar incident radiation w/m2','Diffuse Horizontal incident radiation  (DHI)',
             'Power Generation (kW)','Power Generation (kWh).1','Co2 Reduction (kg)','Precipitation (mm)'], axis=1, inplace = True)

# Change data type
num_cols = ['MeanWS','MaxGustWS','OpenAirTempInst','OpenAirTempMax','OpenAirTempMin','Module1TempInst','Module1TempMax',
 'Module1TempMin','Module2TempInst','Module2TempMax','Module2TempMin','Module3TempInst','Module3TempMax','Module3TempMin',
 'Module4TempInst','Module4TempMax','Module4TempMin','Module5TempInst','Module5TempMax','Module5TempMin','Module6TempInst',
 'Module6TempMax','Module6TempMin','Precipitation','GlobalSolarRadiation','TiltSolarIrradiance','DiffuseSolarIrradiance','PowerInst',
 'PowerMax','PowerMin','Energy','CO2Reduction']

data_frame[num_cols] = data_frame[num_cols].apply(pd.to_numeric)

# Add date column
data_frame["Date"] = pd.to_datetime(data_frame["Day"]) + pd.to_timedelta(data_frame["Time"])

# shift the Date column to first position
first_column = data_frame.pop('Date')
data_frame.insert(0,'Date',first_column)

# Drop Day and Time columns
#data_frame.drop(['Day','Time'],axis=1,inplace=True)

data_frame.set_index("Date")

# drop NAN raws
data_frame.dropna(axis=0, subset=['MeanWS'], inplace=True)

data_frame.head()

,Date,Day,Time,MeanWS,MeanWD,MaxGustWS,MaxGustWD,OpenAirTempInst,OpenAirTempMax,OpenAirTempMin,Module1TempInst,Module1TempMax,Module1TempMin,Module2TempInst,Module2TempMax,Module2TempMin,Module3TempInst,Module3TempMax,Module3TempMin,Module4TempInst,Module4TempMax,Module4TempMin,Module5TempInst,Module5TempMax,Module5TempMin,Module6TempInst,Module6TempMax,Module6TempMin,Precipitation,GlobalSolarRadiation,TiltSolarIrradiance,DiffuseSolarIrradiance,PowerInst,PowerMax,PowerMin,Energy,CO2Reduction
1,2013-01-01 01:00:00,2013-01-01,01:00:00,3.9,W,6.0,WSW,24.1,24.1,23.9,22.9,22.9,22.7,22.2,22.2,22.0,22.1,22.1,21.8,21.7,21.7,21.5,22.0,22.0,21.9,22.3,22.3,22.1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,2013-01-01 02:00:00,2013-01-01,02:00:00,3.0,WSW,6.2,W,24.2,24.3,24.1,22.8,23.0,22.6,22.1,22.3,22.0,21.9,22.1,21.8,21.6,21.8,21.6,22.0,22.1,21.9,22.2,22.4,22.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2013-01-01 03:00:00,2013-01-01,03:00:00,4.8,W,7.8,W,24.8,24.8,24.2,23.5,23.5,22.8,22.8,22.8,22.1,22.7,22.7,22.0,22.3,22.3,21.6,22.6,22.6,22.0,22.8,22.8,22.2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,2013-01-01 04:00:00,2013-01-01,04:00:00,6.1,W,11.3,W,24.1,24.9,24.1,23.4,23.9,23.3,22.7,23.2,22.7,22.5,23.0,22.5,22.0,22.5,22.0,22.4,22.9,22.4,22.6,23.1,22.6,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,2013-01-01 05:00:00,2013-01-01,05:00:00,4.7,WSW,13.1,W,23.2,24.1,23.2,22.1,23.4,22.1,21.4,22.7,21.4,21.3,22.5,21.2,20.9,22.0,20.8,21.2,22.4,21.2,21.5,22.6,21.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:
#Save data in csv format
data_frame.to_csv('data_2013_Jan_Aug,Dec.csv',index=False)

#### Extract and preprocess 2013_Sep to 2013_December

In [57]:
# specifiying the path in the csv files

path_2013_Sep = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Sep'
path_2013_Oct = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Oct'
path_2013_Nov = 'C:\\Users\\DELL\\Documents\\Ushani\\Data Science\\Uni Malaya\\Courses\\Semester - 3\\Project\\Data\\SEA\\2013 Nov'

path = [path_2013_Sep,path_2013_Oct,path_2013_Nov]

In [58]:
# defining an empty list to store content
data_frame_1 = pd.DataFrame()
content = []

for files in path:
    csv_files = glob.glob(files + "/*.csv")
    #csv_files = sorted(glob.glob(os.path.join(path,"*.xlsx")),key = len)

    # loop over the list of csv files
    for f in csv_files:
  
        # read the csv file
        df = pd.read_csv(f)
        
         # drop raws
        df.drop([0], inplace=True)
        
        # insert day column
        day = f.split("\\")[-1].split(' ')[0].split('.')[-2]
        df.insert(0,'Day',day)
    
        # content.append(f)
        content.append(df)

# converting content to data frame
data_frame_1 = pd.concat(content)

# Remove '\n' 
data_frame_1 = data_frame_1.replace('\n','', regex=True)

# Rename Columns
data_frame_1.rename(columns = {'Time\n':'Time','Mean\n':'MeanWS','Unnamed: 2':'MeanWD','Max Gust\n':'MaxGustWS','Unnamed: 4':'MaxGustWD',
                         'Open Air Temperature(deg.C)\n':'OpenAirTempInst','Unnamed: 6':'OpenAirTempMax','Unnamed: 7':'OpenAirTempMin',
                        'Module Temperature 1(deg.C)\n':'Module1TempInst','Unnamed: 9':'Module1TempMax','Unnamed: 10':'Module1TempMin',
                        'Module Temperature 2(deg.C)\n':'Module2TempInst','Unnamed: 12':'Module2TempMax','Unnamed: 13':'Module2TempMin',
                        'Module Temperature 3(deg.C)\n':'Module3TempInst','Unnamed: 15':'Module3TempMax','Unnamed: 16':'Module3TempMin',
                        'Module Temperature 4(deg.C)\n':'Module4TempInst','Unnamed: 18':'Module4TempMax','Unnamed: 19':'Module4TempMin',
                        'Module Temperature 5(deg.C)\n':'Module5TempInst','Unnamed: 21':'Module5TempMax','Unnamed: 22':'Module5TempMin',
                        'Module Temperature 6(deg.C)\n':'Module6TempInst','Unnamed: 24':'Module6TempMax','Unnamed: 25':'Module6TempMin',
                        'Generating Power(kW)\n':'PowerInst','Unnamed: 31':'PowerMax','Unnamed: 32':'PowerMin','Precipitation\n(mm)\n':'Precipitation',
                        'Pyranometer\n(MJ/m2)\n':'GlobalSolarRadiation','Tilt Solar Irradiance (MJ/m2)\n':'TiltSolarIrradiance',
                        'Diffuse Solar Irradiance (MJ/m2)\n':'DiffuseSolarIrradiance','Power Generation (kWh)\n': 'Energy','CO2\nReduction\n(c-kg)\n':'CO2Reduction'},inplace=True)

# drop columns
data_frame_1.drop(['Unnamed: 35','Time (hrs)','Mean Module Temperature (deg oC)','Mean Open Air Temperature (deg oC)',
             'Global horizontal irradiance (GHI) W/m2','Tilt solar incident radiation w/m2','Diffuse Horizontal incident radiation  (DHI)',
             'Power Generation (kW)','Power Generation (kWh)','Co2 Reduction (kg)','Precipitation (mm)'], axis=1, inplace = True)


# Change data type
num_cols = ['MeanWS','MaxGustWS','OpenAirTempInst','OpenAirTempMax','OpenAirTempMin','Module1TempInst','Module1TempMax',
 'Module1TempMin','Module2TempInst','Module2TempMax','Module2TempMin','Module3TempInst','Module3TempMax','Module3TempMin',
 'Module4TempInst','Module4TempMax','Module4TempMin','Module5TempInst','Module5TempMax','Module5TempMin','Module6TempInst',
 'Module6TempMax','Module6TempMin','Precipitation','GlobalSolarRadiation','TiltSolarIrradiance','DiffuseSolarIrradiance','PowerInst',
 'PowerMax','PowerMin','Energy','CO2Reduction']


data_frame_1[num_cols] = data_frame_1[num_cols].apply(pd.to_numeric)

#convert time in the format hh:mm:ss
#data_frame_1["Time"] = [x + ':00' for x in data_frame_1["Time"]]

#data_frame_1['Time'] = pd.to_timedelta(data_frame_1.pop('Time') + ':00')
data_frame_1['Time1'] = pd.to_timedelta(data_frame_1['Time'] + ':00')

# Add date column
data_frame_1["Date"] = pd.to_datetime(data_frame_1["Day"]) + pd.to_timedelta(data_frame_1["Time1"])

# shift the Date column to first position
first_column = data_frame_1.pop('Date')
data_frame_1.insert(0,'Date',first_column)

# Drop Day and Time columns
data_frame_1.drop(['Time1'],axis=1,inplace=True)

data_frame_1.set_index("Date")

# drop NAN raws
data_frame_1.dropna(axis=0, subset=['MeanWS'], inplace=True)

data_frame_1.head()

,Date,Day,Time,MeanWS,MeanWD,MaxGustWS,MaxGustWD,OpenAirTempInst,OpenAirTempMax,OpenAirTempMin,Module1TempInst,Module1TempMax,Module1TempMin,Module2TempInst,Module2TempMax,Module2TempMin,Module3TempInst,Module3TempMax,Module3TempMin,Module4TempInst,Module4TempMax,Module4TempMin,Module5TempInst,Module5TempMax,Module5TempMin,Module6TempInst,Module6TempMax,Module6TempMin,Precipitation,GlobalSolarRadiation,TiltSolarIrradiance,DiffuseSolarIrradiance,PowerInst,PowerMax,PowerMin,Energy,CO2Reduction
1,2013-09-01 00:00:00,2013-09-01,00:00,1.1,WSW,3.1,SW,25.5,25.9,25.5,22.8,23.5,22.8,22.1,22.8,22.1,22.0,22.7,22.0,21.8,22.8,21.8,22.2,23.1,22.2,22.3,23.3,22.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2013-09-01 01:00:00,2013-09-01,01:00,2.2,WSW,4.7,W,25.4,25.5,25.2,24.4,24.4,24.0,23.7,23.8,23.4,23.7,23.7,23.3,23.1,23.1,22.8,23.5,23.5,23.2,23.7,23.7,23.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2013-09-01 02:00:00,2013-09-01,02:00,2.9,WSW,9.2,WSW,24.2,25.4,24.1,23.2,24.5,23.2,22.5,23.9,22.5,22.5,23.8,22.5,21.9,23.2,21.9,22.3,23.6,22.3,22.6,23.9,22.6,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2013-09-01 03:00:00,2013-09-01,03:00,3.6,SW,9.4,WSW,24.0,24.3,23.8,23.2,23.6,23.1,22.6,22.9,22.5,22.5,22.9,22.4,21.9,22.2,21.8,22.3,22.6,22.2,22.7,23.0,22.5,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5,2013-09-01 04:00:00,2013-09-01,04:00,2.7,SW,4.8,SW,24.1,24.2,24.0,23.3,23.4,23.2,22.6,22.7,22.5,22.6,22.7,22.5,22.0,22.1,21.9,22.4,22.4,22.3,22.7,22.8,22.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [59]:
data_frame_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2185 entries, 1 to 24
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    2185 non-null   datetime64[ns]
 1   Day                     2185 non-null   object
 2   Time                    2185 non-null   object
 3   MeanWS                  2185 non-null   float64
 4   MeanWD                  2185 non-null   object
 5   MaxGustWS               2185 non-null   float64
 6   MaxGustWD               2185 non-null   object
 7   OpenAirTempInst         2185 non-null   float64
 8   OpenAirTempMax          2185 non-null   float64
 9   OpenAirTempMin          2185 non-null   float64
 10  Module1TempInst         2185 non-null   float64
 11  Module1TempMax          2185 non-null   float64
 12  Module1TempMin          2185 non-null   float64
 13  Module2TempInst         2185 non-null   float64
 14  Module2TempMax          2185 non-null   float64
 15  Module2TempMin          2185 non-null   float64
 16  Module3TempInst         2185 non-null   float64
 17  Module3TempMax          2185 non-null   float64
 18  Module3TempMin          2185 non-null   float64
 19  Module4TempInst         2185 non-null   float64
 20  Module4TempMax          2185 non-null   float64
 21  Module4TempMin          2185 non-null   float64
 22  Module5TempInst         2185 non-null   float64
 23  Module5TempMax          2185 non-null   float64
 24  Module5TempMin          2185 non-null   float64
 25  Module6TempInst         2185 non-null   float64
 26  Module6TempMax          2185 non-null   float64
 27  Module6TempMin          2185 non-null   float64
 28  Precipitation           2185 non-null   float64
 29  GlobalSolarRadiation    2185 non-null   float64
 30  TiltSolarIrradiance     2185 non-null   float64
 31  DiffuseSolarIrradiance  2185 non-null   float64
 32  PowerInst               2164 non-null   float64
 33  PowerMax                2172 non-null   float64
 34  PowerMin                2172 non-null   float64
 35  Energy                  2185 non-null   float64
 36  CO2Reduction            2185 non-null   float64
dtypes: datetime64[ns](1), float64(32), object(4)
memory usage: 648.7+ KB

In [60]:
#Save data in csv format
data_frame_1.to_csv('data_2013_Sep_Nov.csv',index=False)

In [61]:
# Add 2 data frames
data_frame_2013 = data_frame.append(data_frame_1,ignore_index=True)
data_frame_2013.head()

,Date,Day,Time,MeanWS,MeanWD,MaxGustWS,MaxGustWD,OpenAirTempInst,OpenAirTempMax,OpenAirTempMin,Module1TempInst,Module1TempMax,Module1TempMin,Module2TempInst,Module2TempMax,Module2TempMin,Module3TempInst,Module3TempMax,Module3TempMin,Module4TempInst,Module4TempMax,Module4TempMin,Module5TempInst,Module5TempMax,Module5TempMin,Module6TempInst,Module6TempMax,Module6TempMin,Precipitation,GlobalSolarRadiation,TiltSolarIrradiance,DiffuseSolarIrradiance,PowerInst,PowerMax,PowerMin,Energy,CO2Reduction
0,2013-01-01 01:00:00,2013-01-01,01:00:00,3.9,W,6.0,WSW,24.1,24.1,23.9,22.9,22.9,22.7,22.2,22.2,22.0,22.1,22.1,21.8,21.7,21.7,21.5,22.0,22.0,21.9,22.3,22.3,22.1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2013-01-01 02:00:00,2013-01-01,02:00:00,3.0,WSW,6.2,W,24.2,24.3,24.1,22.8,23.0,22.6,22.1,22.3,22.0,21.9,22.1,21.8,21.6,21.8,21.6,22.0,22.1,21.9,22.2,22.4,22.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2013-01-01 03:00:00,2013-01-01,03:00:00,4.8,W,7.8,W,24.8,24.8,24.2,23.5,23.5,22.8,22.8,22.8,22.1,22.7,22.7,22.0,22.3,22.3,21.6,22.6,22.6,22.0,22.8,22.8,22.2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,2013-01-01 04:00:00,2013-01-01,04:00:00,6.1,W,11.3,W,24.1,24.9,24.1,23.4,23.9,23.3,22.7,23.2,22.7,22.5,23.0,22.5,22.0,22.5,22.0,22.4,22.9,22.4,22.6,23.1,22.6,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,2013-01-01 05:00:00,2013-01-01,05:00:00,4.7,WSW,13.1,W,23.2,24.1,23.2,22.1,23.4,22.1,21.4,22.7,21.4,21.3,22.5,21.2,20.9,22.0,20.8,21.2,22.4,21.2,21.5,22.6,21.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [62]:
data_frame_2013.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8761 entries, 0 to 8760
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    8761 non-null   datetime64[ns]
 1   Day                     8761 non-null   object
 2   Time                    8761 non-null   object
 3   MeanWS                  8761 non-null   float64
 4   MeanWD                  8761 non-null   object
 5   MaxGustWS               8761 non-null   float64
 6   MaxGustWD               8761 non-null   object
 7   OpenAirTempInst         8761 non-null   float64
 8   OpenAirTempMax          8761 non-null   float64
 9   OpenAirTempMin          8761 non-null   float64
 10  Module1TempInst         8761 non-null   float64
 11  Module1TempMax          8761 non-null   float64
 12  Module1TempMin          8761 non-null   float64
 13  Module2TempInst         8761 non-null   float64
 14  Module2TempMax          8761 non-null   float64
 15  Module2TempMin          8761 non-null   float64
 16  Module3TempInst         8761 non-null   float64
 17  Module3TempMax          8761 non-null   float64
 18  Module3TempMin          8761 non-null   float64
 19  Module4TempInst         8761 non-null   float64
 20  Module4TempMax          8761 non-null   float64
 21  Module4TempMin          8761 non-null   float64
 22  Module5TempInst         8617 non-null   float64
 23  Module5TempMax          8617 non-null   float64
 24  Module5TempMin          8632 non-null   float64
 25  Module6TempInst         8761 non-null   float64
 26  Module6TempMax          8761 non-null   float64
 27  Module6TempMin          8761 non-null   float64
 28  Precipitation           8761 non-null   float64
 29  GlobalSolarRadiation    8761 non-null   float64
 30  TiltSolarIrradiance     8761 non-null   float64
 31  DiffuseSolarIrradiance  8761 non-null   float64
 32  PowerInst               8711 non-null   float64
 33  PowerMax                8744 non-null   float64
 34  PowerMin                8744 non-null   float64
 35  Energy                  8761 non-null   float64
 36  CO2Reduction            8761 non-null   float64
dtypes: datetime64[ns](1), float64(32), object(4)
memory usage: 2.5+ MB

In [63]:
# Sort data based on date
data_frame_2013 = data_frame_2013.sort_values(by='Date',ascending=True)

In [64]:
#Save data in csv format
data_frame_2013.to_csv('Data_2013.csv',index=False)

## 1.6 Treat missing values

Data for following dates were missing (2013-07-31 10:00 - 17:00, 2013-08-29, 2013-08-30, 2013-08-31, 2013-09-03, 2013-10-10, 2013-12-16)
Those were filled from the data of previous day.

## 1.7 Join All data (2011,2012,2013)

In [65]:
data_frame_2011_2012 = data_frame_2011.append(data_frame_2012_all,ignore_index= True)
data_frame_all = data_frame_2011_2012.append(data_frame_2013,ignore_index= True)

In [66]:
data_frame_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21471 entries, 0 to 21470
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    21471 non-null  datetime64[ns]
 1   Day                     21471 non-null  object
 2   Time                    21471 non-null  object
 3   MeanWS                  21471 non-null  float64
 4   MeanWD                  21471 non-null  object
 5   MaxGustWS               21471 non-null  float64
 6   MaxGustWD               21471 non-null  object
 7   OpenAirTempInst         21471 non-null  float64
 8   OpenAirTempMax          21471 non-null  float64
 9   OpenAirTempMin          21471 non-null  float64
 10  Module1TempInst         21471 non-null  float64
 11  Module1TempMax          21471 non-null  float64
 12  Module1TempMin          21471 non-null  float64
 13  Module2TempInst         21471 non-null  float64
 14  Module2TempMax          21471 non-null  float64
 15  Module2TempMin          21471 non-null  float64
 16  Module3TempInst         21471 non-null  float64
 17  Module3TempMax          21471 non-null  float64
 18  Module3TempMin          21471 non-null  float64
 19  Module4TempInst         21471 non-null  float64
 20  Module4TempMax          21471 non-null  float64
 21  Module4TempMin          21471 non-null  float64
 22  Module5TempInst         21327 non-null  float64
 23  Module5TempMax          21327 non-null  float64
 24  Module5TempMin          21342 non-null  float64
 25  Module6TempInst         21471 non-null  float64
 26  Module6TempMax          21471 non-null  float64
 27  Module6TempMin          21471 non-null  float64
 28  Precipitation           21387 non-null  float64
 29  GlobalSolarRadiation    21471 non-null  float64
 30  TiltSolarIrradiance     21471 non-null  float64
 31  DiffuseSolarIrradiance  21471 non-null  float64
 32  PowerInst               21321 non-null  float64
 33  PowerMax                21403 non-null  float64
 34  PowerMin                21403 non-null  float64
 35  Energy                  21471 non-null  float64
 36  CO2Reduction            21471 non-null  float64
dtypes: datetime64[ns](1), float64(32), object(4)
memory usage: 6.1+ MB

In [67]:
data_frame_all.shape

(21471, 37)

In [68]:
data_frame_all.head()

,Date,Day,Time,MeanWS,MeanWD,MaxGustWS,MaxGustWD,OpenAirTempInst,OpenAirTempMax,OpenAirTempMin,Module1TempInst,Module1TempMax,Module1TempMin,Module2TempInst,Module2TempMax,Module2TempMin,Module3TempInst,Module3TempMax,Module3TempMin,Module4TempInst,Module4TempMax,Module4TempMin,Module5TempInst,Module5TempMax,Module5TempMin,Module6TempInst,Module6TempMax,Module6TempMin,Precipitation,GlobalSolarRadiation,TiltSolarIrradiance,DiffuseSolarIrradiance,PowerInst,PowerMax,PowerMin,Energy,CO2Reduction
0,2011-07-21 01:00:00,2011-07-21,01:00,5.0,WSW,8.2,WSW,25.6,25.6,25.5,23.9,24.0,23.8,23.4,23.5,23.3,23.4,23.4,23.2,23.0,23.0,22.9,23.3,23.4,23.2,23.8,23.8,23.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2011-07-21 02:00:00,2011-07-21,02:00,3.6,WSW,6.8,SW,25.5,25.6,25.4,24.2,24.2,23.8,23.7,23.7,23.4,23.6,23.6,23.2,23.4,23.4,22.8,23.6,23.6,23.1,24.1,24.1,23.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2011-07-21 03:00:00,2011-07-21,03:00,4.0,WSW,6.7,WSW,25.7,25.8,25.5,23.8,24.2,23.7,23.3,23.7,23.2,23.2,23.6,23.1,23.0,23.5,22.9,23.3,23.8,23.2,23.8,24.4,23.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2011-07-21 04:00:00,2011-07-21,04:00,3.2,WSW,5.9,WSW,25.3,25.7,25.3,23.4,24.0,23.4,23.0,23.5,23.0,22.9,23.4,22.9,22.5,23.2,22.5,22.8,23.5,22.8,23.3,24.0,23.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2011-07-21 05:00:00,2011-07-21,05:00,3.8,WSW,5.5,WSW,25.2,25.4,25.1,23.3,23.5,23.3,22.8,23.0,22.8,22.8,22.9,22.7,22.3,22.5,22.3,22.6,22.8,22.6,23.1,23.2,23.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [69]:
# Sort data based on date
data_frame_all = data_frame_all.sort_values(by='Date',ascending=True)

## 1.8 Add date-time parameters

In [70]:
data_frame_all['Dates'] = pd.to_datetime(data_frame_all.Date.dt.date)
data_frame_all['Year'] = data_frame_all.Date.dt.year
data_frame_all['Month'] = data_frame_all.Date.dt.month
data_frame_all['Day'] = data_frame_all.Date.dt.day
data_frame_all['Hour'] = data_frame_all.Date.dt.hour

In [71]:
data_frame_all.head()

,Date,Day,Time,MeanWS,MeanWD,MaxGustWS,MaxGustWD,OpenAirTempInst,OpenAirTempMax,OpenAirTempMin,Module1TempInst,Module1TempMax,Module1TempMin,Module2TempInst,Module2TempMax,Module2TempMin,Module3TempInst,Module3TempMax,Module3TempMin,Module4TempInst,Module4TempMax,Module4TempMin,Module5TempInst,Module5TempMax,Module5TempMin,Module6TempInst,Module6TempMax,Module6TempMin,Precipitation,GlobalSolarRadiation,TiltSolarIrradiance,DiffuseSolarIrradiance,PowerInst,PowerMax,PowerMin,Energy,CO2Reduction,Dates,Year,Month,Hour
0,2011-07-21 01:00:00,21,01:00,5.0,WSW,8.2,WSW,25.6,25.6,25.5,23.9,24.0,23.8,23.4,23.5,23.3,23.4,23.4,23.2,23.0,23.0,22.9,23.3,23.4,23.2,23.8,23.8,23.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2011-07-21,2011,7,1
1,2011-07-21 02:00:00,21,02:00,3.6,WSW,6.8,SW,25.5,25.6,25.4,24.2,24.2,23.8,23.7,23.7,23.4,23.6,23.6,23.2,23.4,23.4,22.8,23.6,23.6,23.1,24.1,24.1,23.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2011-07-21,2011,7,2
2,2011-07-21 03:00:00,21,03:00,4.0,WSW,6.7,WSW,25.7,25.8,25.5,23.8,24.2,23.7,23.3,23.7,23.2,23.2,23.6,23.1,23.0,23.5,22.9,23.3,23.8,23.2,23.8,24.4,23.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2011-07-21,2011,7,3
3,2011-07-21 04:00:00,21,04:00,3.2,WSW,5.9,WSW,25.3,25.7,25.3,23.4,24.0,23.4,23.0,23.5,23.0,22.9,23.4,22.9,22.5,23.2,22.5,22.8,23.5,22.8,23.3,24.0,23.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2011-07-21,2011,7,4
4,2011-07-21 05:00:00,21,05:00,3.8,WSW,5.5,WSW,25.2,25.4,25.1,23.3,23.5,23.3,22.8,23.0,22.8,22.8,22.9,22.7,22.3,22.5,22.3,22.6,22.8,22.6,23.1,23.2,23.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2011-07-21,2011,7,5

In [72]:
# Change the position of columns
data_frame_all.keys()

Index(['Date', 'Day', 'Time', 'MeanWS', 'MeanWD', 'MaxGustWS', 'MaxGustWD',
       'OpenAirTempInst', 'OpenAirTempMax', 'OpenAirTempMin',
       'Module1TempInst', 'Module1TempMax', 'Module1TempMin',
       'Module2TempInst', 'Module2TempMax', 'Module2TempMin',
       'Module3TempInst', 'Module3TempMax', 'Module3TempMin',
       'Module4TempInst', 'Module4TempMax', 'Module4TempMin',
       'Module5TempInst', 'Module5TempMax', 'Module5TempMin',
       'Module6TempInst', 'Module6TempMax', 'Module6TempMin', 'Precipitation',
       'GlobalSolarRadiation', 'TiltSolarIrradiance', 'DiffuseSolarIrradiance',
       'PowerInst', 'PowerMax', 'PowerMin', 'Energy', 'CO2Reduction', 'Dates',
       'Year', 'Month', 'Hour'],
      dtype='object')

In [73]:
new_cols = ['Date', 'Dates', 'Year', 'Month','Day', 'Hour', 'Time', 'MeanWS', 'MeanWD', 'MaxGustWS', 'MaxGustWD',
       'OpenAirTempInst', 'OpenAirTempMax', 'OpenAirTempMin',
       'Module1TempInst', 'Module1TempMax', 'Module1TempMin',
       'Module2TempInst', 'Module2TempMax', 'Module2TempMin',
       'Module3TempInst', 'Module3TempMax', 'Module3TempMin',
       'Module4TempInst', 'Module4TempMax', 'Module4TempMin',
       'Module5TempInst', 'Module5TempMax', 'Module5TempMin',
       'Module6TempInst', 'Module6TempMax', 'Module6TempMin', 'Precipitation',
       'GlobalSolarRadiation', 'TiltSolarIrradiance', 'DiffuseSolarIrradiance',
       'PowerInst', 'PowerMax', 'PowerMin', 'Energy', 'CO2Reduction' ]
data_frame_all = data_frame_all.reindex(columns = new_cols)

In [74]:
# Drop Time column
data_frame_all.drop(['Time'],axis=1, inplace=True)

In [75]:
data_frame_all.head()

,Date,Dates,Year,Month,Day,Hour,MeanWS,MeanWD,MaxGustWS,MaxGustWD,OpenAirTempInst,OpenAirTempMax,OpenAirTempMin,Module1TempInst,Module1TempMax,Module1TempMin,Module2TempInst,Module2TempMax,Module2TempMin,Module3TempInst,Module3TempMax,Module3TempMin,Module4TempInst,Module4TempMax,Module4TempMin,Module5TempInst,Module5TempMax,Module5TempMin,Module6TempInst,Module6TempMax,Module6TempMin,Precipitation,GlobalSolarRadiation,TiltSolarIrradiance,DiffuseSolarIrradiance,PowerInst,PowerMax,PowerMin,Energy,CO2Reduction
0,2011-07-21 01:00:00,2011-07-21,2011,7,21,1,5.0,WSW,8.2,WSW,25.6,25.6,25.5,23.9,24.0,23.8,23.4,23.5,23.3,23.4,23.4,23.2,23.0,23.0,22.9,23.3,23.4,23.2,23.8,23.8,23.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2011-07-21 02:00:00,2011-07-21,2011,7,21,2,3.6,WSW,6.8,SW,25.5,25.6,25.4,24.2,24.2,23.8,23.7,23.7,23.4,23.6,23.6,23.2,23.4,23.4,22.8,23.6,23.6,23.1,24.1,24.1,23.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2011-07-21 03:00:00,2011-07-21,2011,7,21,3,4.0,WSW,6.7,WSW,25.7,25.8,25.5,23.8,24.2,23.7,23.3,23.7,23.2,23.2,23.6,23.1,23.0,23.5,22.9,23.3,23.8,23.2,23.8,24.4,23.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2011-07-21 04:00:00,2011-07-21,2011,7,21,4,3.2,WSW,5.9,WSW,25.3,25.7,25.3,23.4,24.0,23.4,23.0,23.5,23.0,22.9,23.4,22.9,22.5,23.2,22.5,22.8,23.5,22.8,23.3,24.0,23.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2011-07-21 05:00:00,2011-07-21,2011,7,21,5,3.8,WSW,5.5,WSW,25.2,25.4,25.1,23.3,23.5,23.3,22.8,23.0,22.8,22.8,22.9,22.7,22.3,22.5,22.3,22.6,22.8,22.6,23.1,23.2,23.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 1.9 Save data

In [76]:
#Save data in csv format
data_frame_all.to_csv('Data_2011_2012_2013.csv',index=False)